id = "reason"
name = "Reason"
description = "Reason language support"
version = "0.0.1"
schema_version = 1
authors = ["WeetHet <stas.ale66@gmail.com>"]
repository = "https://github.com/weethet/reason-zed"

[language_servers.ocamllsp]
name = "Ocaml/Reason language server"
language = "Reason"

[grammars.reason]
repository = "https://github.com/reasonml-editor/tree-sitter-reason"
commit = "0226cfecaa2257d56d7c3f364f789cba042e403f"

[grammars.dune]
repository = "https://github.com/WHForks/tree-sitter-dune"
commit = "b3f7882e1b9a1d8811011bf6f0de1c74c9c93949"
